export const ACTION_TYPES = {
  INITIALIZE_DATA: 'INITIALIZE_DATA',
  SET_CITIES: 'SET_CITIES',
  CLEAR_PREFERENCES: 'CLEAR_PREFERENCES',
  ADD_PREFERENCE: 'ADD_PREFERENCE',
  REMOVE_PREFERENCE: 'REMOVE_PREFERENCE',
  SET_ERROR: 'SET_ERROR',
  LOAD_MORE: 'LOAD_MORE',
  SEARCH_CITIES: 'SEARCH_CITIES',
  SELECT_VIEW_TYPE: 'SELECT_VIEW_TYPE',
};
