export const ACTION_TYPES = {
  SET_CITIES: 'SET_CITIES',
  SET_FILTER: 'SET_FILTER',
  CLEAR_PREFERENCES: 'CLEAR_PREFERENCES',
  ADD_PREFERENCE: 'ADD_PREFERENCE',
  REMOVE_PREFERENCE: 'REMOVE_PREFERENCE',
};
